CONFIG_ZMK_KEYBOARD_NAME="Forager"
CONFIG_ZMK_POINTING=y

# Enable Idle on 30 secons inact.
CONFIG_ZMK_IDLE_TIMEOUT=30000
# Enable Sleep on 40 minute inact.
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=2400000
# Enable SOFT_OFF behaviour
CONFIG_ZMK_PM_SOFT_OFF=y

# Battery
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# RgbLed
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=40
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_LOW=20
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=5
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
# Windows Base - Blue
# CONFIG_RGBLED_WIDGET_LAYER_0_COLOR=4
# # MacOS Base - Green
# CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=2
# # Win Numpad - White
# CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=7
# # Mac Numpad - White
# CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=7
# # Symbols - Magenta
# CONFIG_RGBLED_WIDGET_LAYER_4_COLOR=5
# # Navigation - Cyan
# CONFIG_RGBLED_WIDGET_LAYER_5_COLOR=6
# # Win Function Keys - Yellow
# CONFIG_RGBLED_WIDGET_LAYER_6_COLOR=3
# # Mac Function Keys - Yellow
# CONFIG_RGBLED_WIDGET_LAYER_7_COLOR=3
# # Win Adjustments - Red
# CONFIG_RGBLED_WIDGET_LAYER_8_COLOR=1
# # Mac Adjustments - Red
# CONFIG_RGBLED_WIDGET_LAYER_9_COLOR=1
# # Connectivity - Red
# CONFIG_RGBLED_WIDGET_LAYER_10_COLOR=1
# Next noes are configured in build.yaml
#CONFIG_RGBLED_WIDGET_BATTERY_SHOW_SELF=n
#CONFIG_RGBLED_WIDGET_BATTERY_SHOW_PERIPHERALS=n
#CONFIG_RGBLED_WIDGET_BATTERY_SHOW_ONLY_PERIPHERALS=n
